
name: Build & Run Docker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (load to local Docker)
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: myapp:local
          load: true           # makes the image available to `docker run`

      - name: Run container
        run: docker run --rm myapp:local

