name: Hello World

on:
  push:
    branches:
      - main   # runs when you push to main branch

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Hello World
        run: echo "Hello, World! 🎉"

