
name: Hello Python (Matrix)

on:
  push:
    branches: ["main"]       # run on push to main
  pull_request:
    branches: ["main"]       # run on PRs targeting main
  workflow_dispatch:          # allow manual run from Actions tab
  schedule:
    - cron: "0 0 * * *"      # run every day at 00:00 UTC

jobs:
  hello:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Show Python version
        run: python -V

      - name: Run script
        run: python src/hello.py

